author: H31IX
database: false
main: net.h31ix.damage.Damage
name: Damage
startup: postworld
url: http://H31IX.NET/
version: '1.0'
commands:
  damage:
    description: Use damage plugin
    usage: /damage
